export const AuthAction = {
        LOGIN: 'LOGIN',
        LOGIN_SUCCESS: 'LOGIN_SUCCESS',
        LOGIN_FAILURE: 'LOGIN_FAILURE',
        LOGOUT: 'LOGOUT',
        REGISTER: 'REGISTER',
        REGISTER_SUCCESS: 'REGISTER_SUCCESS',
        REGISTER_FAILURE: 'REGISTER_FAILURE',
        CLEAR_REGISTER_SUCCESS: 'CLEAR_REGISTER_SUCCESS',
        AUTH_ERROR: 'AUTH_ERROR',
        GET_ALL: 'GET_ALL',
        GET_ALL_SUCCESS: 'GET_ALL_SUCCESS',
        GET_ALL_FAILURE: 'GET_ALL_FAILURE',
        DELETE: 'DELETE',
        DELETE_SUCCESS: 'DELETE_SUCCESS',
        DELETE_FAILURE: 'DELETE_FAILURE',
    }
;

export const ProductAction = {
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',

    FETCH_PRODUCT: 'FETCH_PRODUCT',
    FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',

    CREATED_PRODUCT_SUCCESS: 'CREATED_PRODUCT_SUCCESS',
    CLEAR_PRODUCT_CREATED: 'CLEAR_PRODUCT_CREATED'
};

export const PageAction = {
    FETCH_HOME: 'FETCH_HOME',
    FETCH_HOME_SUCCESS: 'FETCH_HOME_SUCCESS',
};

export const CartAction = {
    PRODUCT_ADDED_TO_CART: 'PRODUCT_ADDED_TO_CART',
    REMOVE_PRODUCT_FROM_CART: 'REMOVE_PRODUCT_FROM_CART',
    SET_CART: 'SET_CART',
};

export const UiAction = {
    ALERT_SUCCESS: 'ALERT_SUCCESS',
    ALERT_ERROR: 'ALERT_ERROR',
    ALERT_CLEAR: 'ALERT_CLEAR',
    ALERT_INFO: 'ALERT_INFO',

    TOAST_SHOW: 'TOAST_SHOW',
    TOAST_CLEAR: 'TOAST_CLEAR',
    TOAST_SUCCESS: 'TOAST_SUCCESS',
};

export const CommentAction = {
    CREATE_COMMENT: 'CREATE_COMMENT',
};

export const TempDataAction = {
    SET_CART_ITEM_QUANTITY: 'SET_CART_ITEM_QUANTITY',
    CLEAR_CART_ITEM_QUANTITY: 'CLEAR_CART_ITEM_QUANTITY',
    SET_CART_ITEM_QUANTITIES: 'SET_CART_ITEM_QUANTITIES',

};


export const AddressesAction = {
    FETCH_ADDRESSES: 'FETCH_ADDRESSES',
    FETCH_ADDRESSES_SUCCESS: 'FETCH_ADDRESSES_SUCCESS'
};

export const OrdersAction = {
    FETCH_ORDERS: 'FETCH_ORDERS',
    FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
    local: {
        ORDER_SUCCESS: 'ORDER_SUCCESS',
        CLEAR_ORDER_SUCCESS: 'CLEAR_ORDER_SUCCESS',
    }
};

